name: 'Download a Build Artifact'
description: 'Download a build artifact that was previously uploaded in the workflow by the upload-artifact action'
author: 'GitHub'
inputs: 
  name:
    description: 'Artifact name'
    required: false
  path:
    description: 'Destination path'
    required: false
  dontextract:
    description: 'Should the artifact be extracted after downloaded. Default behavior is True'
    required: false
    default: True
runs:
  using: 'node16'
  main: 'dist/index.js'
