name: Licensed

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Check licenses status
    steps:
      - uses: actions/checkout@v2
      - uses: jonabc/setup-licensed@v1
        with:
          version: '3.x'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: npm install
      - run: licensed status
