name: Licensed

on:
  push:
    branches:
      - main
    paths: [package-lock.json]
  pull_request:
    branches: main
    paths: package-lock.json
  workflow_dispatch:

jobs:
  update_licenses_cache:
    runs-on: ubuntu-latest
    name: Update licenses cache
    steps:
      - uses: actions/checkout@v1
      - uses: jonabc/setup-licensed@v1
        with:
          version: '3.x'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: npm install --production
      - uses: jonabc/licensed-ci@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
